"use client";

import { useState } from "react";
import { toast } from "sonner";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ShieldCheck, Smartphone, Mail } from "lucide-react";
import { IconSpinner } from "@/components/auth/shared/icons";
import { TwoFactorSetup } from "@/components/auth/TwoFactorSetup";

type TwoFactorStatus = {
  two_factor_enabled?: boolean;
  two_factor_method?: "EMAIL" | "TOTP" | null;
};

export function SecuritySettings() {
  const queryClient = useQueryClient();
  const [switching, setSwitching] = useState(false);

  const fetchStatus = async (): Promise<TwoFactorStatus> => {
    const res = await fetch("/api/proxy/auth/2fa/status");
    if (!res.ok) {
      throw new Error("Failed to load security settings.");
    }
    const data = await res.json();
    return data.data;
  };

  const { data: status, isPending: loading } = useQuery({
    queryKey: ["two-factor-status"],
    queryFn: fetchStatus,
    staleTime: 60 * 1000,
  });

  const handleSwitched = (result: TwoFactorStatus) => {
    setSwitching(false);
    queryClient.setQueryData(["two-factor-status"], result);
    toast.success(
      `Two-factor authentication is now set to ${result.two_factor_method === "TOTP" ? "authenticator app" : "email"}.`,
    );
  };

  if (loading) {
    return (
      <div className="flex h-40 items-center justify-center">
        <IconSpinner className="w-8 h-8 animate-spin text-[#2D6A4F]" />
      </div>
    );
  }

  return (
    <div className="max-w-4xl">
      <div className="bg-white dark:bg-[#121212] border border-gray-200 dark:border-gray-800 rounded-3xl p-6 md:p-8 shadow-sm">
        <div className="flex items-center gap-3 mb-8 pb-6 border-b border-gray-100 dark:border-gray-800">
          <div className="w-10 h-10 rounded-full bg-[#2D6A4F]/10 flex items-center justify-center">
            <ShieldCheck className="w-6 h-6 text-[#2D6A4F]" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">
              Two-Factor Authentication
            </h2>
            <p className="text-sm text-gray-500">
              Every account requires 2FA. Choose how you&apos;d like to verify sign-ins.
            </p>
          </div>
        </div>

        {switching ? (
          <TwoFactorSetup
            api={{ kind: "authenticated" }}
            title="Switch your verification method"
            description="Changes take effect immediately, without needing to sign in again."
            currentMethod={status?.two_factor_method}
            onBack={() => setSwitching(false)}
            onComplete={(result) => handleSwitched(result)}
          />
        ) : (
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-xl bg-[#2D6A4F]/10 dark:bg-[#52b788]/10 flex items-center justify-center flex-shrink-0">
                {status?.two_factor_method === "TOTP" ? (
                  <Smartphone className="w-5 h-5 text-[#2D6A4F] dark:text-[#52b788]" />
                ) : (
                  <Mail className="w-5 h-5 text-[#2D6A4F] dark:text-[#52b788]" />
                )}
              </div>
              <div>
                <p className="text-sm font-bold text-gray-900 dark:text-white">
                  {status?.two_factor_method === "TOTP" ? "Authenticator app" : "Email code"}
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  {status?.two_factor_method === "TOTP"
                    ? "Codes are generated by your authenticator app."
                    : "Codes are sent to your email at sign-in."}
                </p>
              </div>
            </div>

            <button
              type="button"
              onClick={() => setSwitching(true)}
              className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#2D6A4F] px-6 text-sm font-semibold text-white transition-all hover:bg-[#1B4332] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2D6A4F] active:scale-[0.98] shadow-md shadow-[#2D6A4F]/20"
            >
              Switch method
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
